-- MySQL Script generated by MySQL Workbench
-- Mon Nov  5 17:22:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema petrolera
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema petrolera
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petrolera` DEFAULT CHARACTER SET utf8 ;
USE `petrolera` ;

-- -----------------------------------------------------
-- Table `petrolera`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petrolera`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `contraseña` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petrolera`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petrolera`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `cedula_persona` VARCHAR(10) NOT NULL,
  `nombre_persona` VARCHAR(90) NOT NULL,
  `usuario_persona` INT NULL,
  `cargo_persona` VARCHAR(30) NOT NULL,
  `correo_persona` VARCHAR(120) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `cedula_persona_UNIQUE` (`cedula_persona` ASC),
  UNIQUE INDEX `usuario_persona_UNIQUE` (`usuario_persona` ASC),
  CONSTRAINT `persona_usuario`
    FOREIGN KEY (`usuario_persona`)
    REFERENCES `petrolera`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petrolera`.`reporte_incidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petrolera`.`reporte_incidente` (
  `id_reporte_incidente` INT NOT NULL AUTO_INCREMENT,
  `nombre_reportero` VARCHAR(90) NOT NULL,
  `cedula_reportero` VARCHAR(10) NOT NULL,
  `fecha_reporte` DATE NOT NULL,
  `nombre_pers_impl` VARCHAR(90) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `prueba_reporte` LONGBLOB NOT NULL,
  `tipo_incidente` VARCHAR(60) NOT NULL,
  `categoria_incidente` VARCHAR(60) NOT NULL,
  `cedula_implicado` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_reporte_incidente`),
  INDEX `reporte_persona_idx` (`cedula_reportero` ASC),
  INDEX `reporte_implicado_idx` (`cedula_implicado` ASC),
  CONSTRAINT `reporte_persona`
    FOREIGN KEY (`cedula_reportero`)
    REFERENCES `petrolera`.`persona` (`cedula_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reporte_implicado`
    FOREIGN KEY (`cedula_implicado`)
    REFERENCES `petrolera`.`persona` (`cedula_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
